if(live_call()) return live_result;
draw_set_font(fnt_papyrus)
draw_set_color(c_black)
draw_set_alpha(0.7);
draw_text(x+11,y+28,"CURRENT ROOM = "+string(room_get_name(room)))
draw_text(x+11,y+42,"WINDOW WIDTH = "+string(global.resolution_current.w))
draw_text(x+11,y+56,"WINDOW HEIGHT = "+string(global.resolution_current.h))

draw_set_alpha(1);
draw_set_color(c_white)
draw_text(x+10,y+28,"CURRENT ROOM = "+string(room_get_name(room)))
draw_text(x+10,y+42,"WINDOW WIDTH = "+string(global.resolution_current.w))
draw_text(x+10,y+56,"WINDOW HEIGHT = "+string(global.resolution_current.h))

 draw_sprite_ext(spr_px, 0, 585, 315, 55, 45, 0, c_black, 0.2)
 draw_set_font(fnt_sans)
 draw_set_color(c_green)
  draw_text(591, 315, string(fps_real))
 draw_set_color(c_lime)
 draw_set_font(fnt_sans)
 draw_text(590, 315, string(fps_real))
 draw_set_font(fnt_sans)
  draw_set_color(c_green)
   draw_text(611, 335, string(fps))
    draw_set_color(c_lime)
  draw_text(610, 335, string(fps))
  draw_set_font(fnt_sans)
  draw_set_alpha(0.7);
  draw_set_color(c_black)
   draw_text(181, 325, ("Instance Count: " + string(instance_count)))	
   draw_set_alpha(1);
  draw_set_color(c_yellow)
  draw_text(180, 465, ("Instance Count: " + string(instance_count)))	
		
 //var col = make_color_hsv((ca % 255), 255, 255)
 //draw_set_color(col)
 //draw_set_font(fnt_papyrus);
 //draw_text_ext_transformed(480, 392, "DEBUG", 120, 160, 2, 2, 0)
 // x1 = (480 + (sin(degtorad(ca)) * 20))
  //y1 = (392 + (cos(degtorad(ca)) * 20))
  //x2 = (480 + (sin(degtorad((ca + 120))) * 20))
  //y2 = (392 + (cos(degtorad((ca + 120))) * 20))
  //x3 = (480 + (sin(degtorad((ca + 240))) * 20))
  //y3 = (392 + (cos(degtorad((ca + 240))) * 20))
  //gpu_set_blendmode(bm_add)
  //var col1 = make_color_rgb(255, 0, 0)
  //var col2 = make_color_rgb(0, 255, 0)
  //var col3 = make_color_rgb(0, 0, 255)
  //draw_text_ext_transformed_color(x3, y3, "DEBUG", 120, 160, 2, 2, 0, col1, col3, col3, col3, 1)
  //draw_text_ext_transformed_color(x2, y2, "DEBUG", 120, 160, 2, 2, 0, col1, col2, col2, col2, 1)
  //draw_text_ext_transformed_color(x1, y1, "DEBUG", 120, 160, 2, 2, 0, col1, col1, col1, col1, 1)
  //gpu_set_blendmode(bm_normal)
